# Generated by Django 6.0.5 on 2026-05-09 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, unique=True)),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
                ('sample_condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('hemolyzed', 'Hemolyzed')], default='good', max_length=30)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('received', 'Received in Lab'), ('processing', 'Processing'), ('completed', 'Completed')], default='collected', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('collected_by', models.ForeignKey(limit_choices_to={'role': 'phlebotomist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='orders.laborder')),
            ],
        ),
    ]
