# Generated by Django 6.0.5 on 2026-05-10 16:39

import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(validators=[patients.models.validate_dob]),
        ),
    ]
